name: first_workflow

on:
 workflow_dispatch:
 
jobs:
 firstJob:
  runs_on: ubuntu_latest
   steps:
    - name: firstScript
      shell: bash
      run: echo Hello world Git Actions
    - name: secondScript
      shell: bash
      run: echo second Script
 secondJob:
  runs_on: ubuntu_latest
   steps:
    - name: firstScript
      shell: bash
      run: |
       echo Hello Second Job
       echo Hello Multi Line
     
